/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author HP
 */
public class User_Management extends javax.swing.JFrame {
    
    Connection conn;
    Statement s;
    ResultSet  rs;
    
    String UID = null;
    
    
    /**
     * Creates new form User_Management
     */
    public User_Management() {
        initComponents();
        
      // 
        
      //  btnEditUser.setVisible(false);
      btnCancel.requestFocus();
      jlmbLogUser.setText(Login_Details.Username);
      jlmbLogUserType.setText(Login_Details.Usertype);
        
        try
             {
                DB_Connection obj=new DB_Connection();
                conn = obj.getConnection();
                
                fetch_data();                 
            }
         catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error encounterd while entering connection" +e);
            }      
        
    }
    
    
    
    public void fetch_data(){
    
        try{
        
            String Sql="SELECT * FROM `users`";
                
                s=conn.createStatement();
        
                rs = s.executeQuery(Sql);
                
                
                DefaultTableModel model = new DefaultTableModel();
                
                model.addColumn("User ID");
                model.addColumn("Username");
                model.addColumn("User Type");
                model.addColumn("Full Name");
               
                
                while(rs.next()){
                
                    String Values[] = {rs.getString(1), rs.getString(2), rs.getString(4), rs.getString(5)};
                    model.addRow(Values);
                    userTable.setModel(model);
                
                }
        
        
        }
        
        catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error encounterd while entering connection" +e);
            }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUserSerach2 = new javax.swing.JTextField();
        iconSerach2 = new javax.swing.JLabel();
        jlmbLogUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlmbLogUserType = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnEditUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        txtUserSerach2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUserSerach2.setForeground(new java.awt.Color(102, 102, 102));
        txtUserSerach2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserSerach2.setText("Enter UserID 'Serach Detalis'");
        txtUserSerach2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtUserSerach2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserSerach2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserSerach2FocusLost(evt);
            }
        });
        txtUserSerach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserSerach2ActionPerformed(evt);
            }
        });
        txtUserSerach2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserSerach2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserSerach2KeyReleased(evt);
            }
        });

        iconSerach2.setBackground(new java.awt.Color(255, 51, 0));
        iconSerach2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\search.png")); // NOI18N
        iconSerach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSerach2MouseClicked(evt);
            }
        });
        iconSerach2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iconSerach2KeyPressed(evt);
            }
        });

        jlmbLogUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlmbLogUser.setForeground(new java.awt.Color(255, 255, 102));
        jlmbLogUser.setText("Uname");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/User-icon.png"))); // NOI18N

        jlmbLogUserType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlmbLogUserType.setForeground(new java.awt.Color(153, 255, 153));
        jlmbLogUserType.setText("Utype");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/Connected-icon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER MANAGER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(txtUserSerach2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconSerach2)
                .addGap(85, 85, 85)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlmbLogUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlmbLogUser, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlmbLogUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jlmbLogUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUserSerach2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSerach2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "User Type", "Full Name"
            }
        ));
        userTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                userTableMouseMoved(evt);
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userTableMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEditUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/user-edit-icon.png"))); // NOI18N
        btnEditUser.setText("Edit User");
        btnEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditUserMouseClicked(evt);
            }
        });
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnAddUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/user-add-icon.png"))); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 255, 204));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/images/Button-Close-icon.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addGap(45, 45, 45)
                .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
       
        btnEditUser.setVisible(true);
        int i = userTable.getSelectedRow();
        TableModel model=userTable.getModel();
        
        UID = model.getValueAt(i,0).toString();
        
        
        
        
       // JOptionPane.showMessageDialog(null,"you selected Uid Is : "+UID);
    }//GEN-LAST:event_userTableMouseClicked

    private void userTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseEntered
        // TODO add your handling code here:
        
       
      // userTable.setForeground(new Color(100,255,255));
    }//GEN-LAST:event_userTableMouseEntered

    private void userTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userTableMouseMoved

    private void userTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseExited
        // TODO add your handling code here:
        
         //userTable.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_userTableMouseExited

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        // TODO add your handling code here:
        if(UID == null){
           JOptionPane.showMessageDialog(null,"Pleace Select A User For Edit"); 
        }
        
        else{
            
            String Sql="SELECT * FROM `users` WHERE user_id ='"+UID+"' ";
            
            try{
                
                s=conn.createStatement();
        
                ResultSet  rs = s.executeQuery(Sql);
                
                while (rs.next()){
                    
                      String Uty = rs.getString("user_type");
                
                      if(Login_Details.Usertype.equals("Admin")){
                          
                          
                          Admin_create_new_user A =new Admin_create_new_user(UID);
                          A.setVisible(true);
                          this.setVisible(false);
                      
                      }
                      else{
                          
                          if(Uty.equals("Admin")||Uty.equals("Manager")){
                          
                                JOptionPane.showMessageDialog(null,"You Can't Acssess this account ! 'Because This Account Only Can Accsess By Admin'.");
                          }
                          else{
                              
                              Admin_create_new_user A =new Admin_create_new_user(UID);
                              A.setVisible(true);
                              this.setVisible(false);
                          
                          }
                      
                      
                      }
                
                
                }
            
            
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error encounterd while entering connection" +e);
            }   
        
            
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditUserMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnEditUserMouseClicked

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
      fetch_data();
      UID=null;
      Admin_create_new_user A =new Admin_create_new_user(UID);
      A.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void txtUserSerach2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserSerach2KeyReleased
        // TODO add your handling code here:
        txtUserSerach2.setText(txtUserSerach2.getText().toUpperCase());
    }//GEN-LAST:event_txtUserSerach2KeyReleased

    private void txtUserSerach2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserSerach2KeyPressed
        // TODO add your handling code here:

        String User_ID = txtUserSerach2.getText();
        int length = User_ID.length();

        if(length<10 && evt.getExtendedKeyCode()!=KeyEvent.VK_SPACE)
        {
            txtUserSerach2.setEditable(true);
        }

        else
        {
            txtUserSerach2.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtUserSerach2.setEditable(true);
            }
            else
            {
                txtUserSerach2.setEditable(false);

            }
        }
    }//GEN-LAST:event_txtUserSerach2KeyPressed

    private void txtUserSerach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserSerach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserSerach2ActionPerformed

    private void txtUserSerach2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserSerach2FocusLost
        // TODO add your handling code here:
        if(txtUserSerach2.getText().equals("")){

            txtUserSerach2.setText("Enter UserID 'Serach Detalis'");
            txtUserSerach2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtUserSerach2FocusLost

    private void txtUserSerach2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserSerach2FocusGained
        // TODO add your handling code here:
        if(txtUserSerach2.getText().equals("Enter UserID 'Serach Detalis'")){

            txtUserSerach2.setText("");
            txtUserSerach2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtUserSerach2FocusGained

    private void iconSerach2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iconSerach2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconSerach2KeyPressed

    private void iconSerach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSerach2MouseClicked
        // TODO add your handling code here:

        String Uid = txtUserSerach2.getText();

        
            
            String Sql="SELECT * FROM `users` WHERE user_id ='"+Uid+"' ";
            
            try{
                
                s=conn.createStatement();
        
                ResultSet  rs = s.executeQuery(Sql);
                
                if (rs.next()){
                    
                      String Uty = rs.getString("user_type");
                
                      if(Login_Details.Usertype.equals("Admin")){
                          
                         
                          JOptionPane.showMessageDialog(null,"Record Found");
                          Admin_create_new_user A =new Admin_create_new_user(Uid);
                          A.setVisible(true);
                          this.setVisible(false);
                          
                      
                      }
                      else{
                          
                          if(Uty.equals("Admin")||Uty.equals("Manager")){
                          
                                JOptionPane.showMessageDialog(null,"You Can't Acssess this account ! 'Because This Account Only Can Accsess By Admin'.");
                          }
                          else{
                              
                               
                              JOptionPane.showMessageDialog(null,"Record Found");
                              Admin_create_new_user A =new Admin_create_new_user(Uid);
                              A.setVisible(true);
                              this.setVisible(false);
                              
                          
                          }
                      
                      
                      }
                
                
                }
                
                else{
                        
                        JOptionPane.showMessageDialog(null,"Record Not Found");
                        txtUserSerach2.setText("Enter UserID 'Serach Detalis'");
                        txtUserSerach2.setForeground(new Color(153,153,153));
                        btnAddUser.requestFocus();
                        
                    }
            
            
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error encounterd while entering connection" +e);
            }   
        
            
        
    }//GEN-LAST:event_iconSerach2MouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:

        Account_Management A = new Account_Management();
        A.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JLabel iconSerach2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlmbLogUser;
    private javax.swing.JLabel jlmbLogUserType;
    private javax.swing.JTextField txtUserSerach2;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
